# Generated by Django 4.2.30 on 2026-07-23 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Setting',
                'verbose_name_plural': 'Admin Settings',
                'db_table': 'portal_admin_settings',
            },
        ),
        migrations.CreateModel(
            name='HotspotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('issue_type', models.CharField(max_length=50)),
                ('report_count', models.IntegerField(default=1)),
                ('avg_risk_score', models.FloatField(default=0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotspot Analysis',
                'verbose_name_plural': 'Hotspot Analyses',
                'db_table': 'portal_hotspot_analysis',
                'ordering': ['-report_count'],
                'unique_together': {('location', 'issue_type')},
            },
        ),
        migrations.CreateModel(
            name='CivicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of the civic issue')),
                ('location', models.CharField(default='Unknown', help_text='Location/address where the issue is reported', max_length=255)),
                ('issue', models.CharField(choices=[('Road Damage', 'Road Damage'), ('Water Leakage', 'Water Leakage'), ('Garbage', 'Garbage & Waste'), ('Electricity', 'Electricity Hazard'), ('Streetlight', 'Streetlight Failure'), ('Flood', 'Flooding/Waterlogging'), ('Fire Emergency', 'Fire Emergency'), ('Tree Fall', 'Tree Fall/Obstruction'), ('General Civic Issue', 'General Civic Issue')], default='General Civic Issue', help_text='AI-classified issue type', max_length=50)),
                ('priority', models.CharField(choices=[('Critical', 'Critical - Immediate Action Required'), ('High', 'High - Urgent'), ('Medium', 'Medium - Standard'), ('Low', 'Low - Maintenance')], default='Medium', help_text='Priority level from AI triage', max_length=20)),
                ('department', models.CharField(default='Municipal Corporation', help_text='Recommended responsible department', max_length=100)),
                ('confidence', models.CharField(choices=[('High', 'High (>75%)'), ('Medium', 'Medium (50-75%)'), ('Low', 'Low (<50%)')], default='Medium', help_text='AI confidence in classification', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 risk severity score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reason', models.TextField(blank=True, help_text='AI reasoning for classification')),
                ('advice', models.TextField(blank=True, help_text='AI-generated advice for the reporter')),
                ('suggested_action', models.TextField(blank=True, help_text='Suggested action for responsible department')),
                ('photo', models.ImageField(blank=True, help_text='Photo evidence of the issue', null=True, upload_to='reports/%Y/%m/%d/')),
                ('upvotes', models.IntegerField(default=1, help_text='Community support/verification count', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.IntegerField(choices=[(0, 'Approved - Valid'), (1, 'Flagged - Spam/Invalid'), (2, 'Pending - Needs Review')], default=0, help_text='Report moderation status (0=valid, 1=spam, 2=needs_review)')),
                ('moderator_notes', models.TextField(blank=True, help_text='Admin notes on moderation decision')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the report was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was marked resolved', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Reporter IP (for duplicate detection)', null=True)),
                ('device_id', models.CharField(blank=True, help_text='Device identifier (PWA offline support)', max_length=100)),
            ],
            options={
                'verbose_name': 'Civic Report',
                'verbose_name_plural': 'Civic Reports',
                'db_table': 'portal_civic_report',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='portal_civi_submitt_56f401_idx'), models.Index(fields=['issue', '-submitted_at'], name='portal_civi_issue_8d21f4_idx'), models.Index(fields=['priority', '-submitted_at'], name='portal_civi_priorit_0aa7c7_idx'), models.Index(fields=['status', '-submitted_at'], name='portal_civi_status_26dc10_idx'), models.Index(fields=['location', '-submitted_at'], name='portal_civi_locatio_971b5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('report_created', 'Report Submitted'), ('report_modified', 'Report Modified'), ('report_reviewed', 'Report Reviewed'), ('report_deleted', 'Report Deleted'), ('spam_flagged', 'Spam Flagged'), ('upvote_added', 'Upvote Added'), ('admin_login', 'Admin Login'), ('admin_action', 'Admin Action'), ('export_data', 'Data Export'), ('ai_analysis', 'AI Analysis Run')], max_length=50)),
                ('admin_username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='portal.civicreport')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'portal_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='portal_audi_created_09a512_idx'), models.Index(fields=['action'], name='portal_audi_action_908e27_idx')],
            },
        ),
    ]
